### ISSUE TITLE
Ensure ManifestWork created for each DRCluster is recreated if deleted by the user (or other automation)

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#776]
For example in DRPC reconciler manager, we watch for [ManifestWork updates](https://github.com/RamenDR/ramen/blob/3855a6621ce466f5c1d2374d6d4184bd0daadb06/controllers/drplacementcontrol_controller.go#L73) to trigger reconciliation of the related DRPC resource.

Along similar lines, we potentially want to trigger a reconcile of DRCluster resource based on certain ManifestWork changes that it creates. One such would be to recreate it if deleted (IOW reconcile DRCluster resource if the resource is deleted) (which may need finalizers on the resource?).

Another means to address this would be to look at the [ManagedClusterView](https://github.com/RamenDR/ramen/pull/526) for the created ManifestWork and if that reports errors (or missing resources), then to reconcile DRCluster to recreate the same.

**Comment by raghavendra-talur** [comment]
@ELENAGER Can you check if you recent fixes around watch for ManifestWork fixes this issue?

**Comment by raghavendra-talur** [comment]
Fixed by #892

**Comment by ShyamsundarR** [comment]
The mentioned PR does not fix the reported issue, reopening...
